package com.o2hlink.activa.connection.message;

import com.o2hlink.activa.Activa;

/**
 * @author Adrian Rejas<P>
 * 
 * This class deals with the creation of the main message, once the data to be sent has been created.
 * The data will be stored as a single String, cause this data can be very different from a message 
 * to another.
 */

public class Message {
	private String data;
	
	public Message() {
		this.data = null;
	}
	
	public Message(String data) {
		this.data = data;
	}
	
	public String toString() {
		String returned;
		returned = "Object of class Message generated by user " + 
			Activa.myMobileManager.user.getName();
		returned += " with password " + Activa.myMobileManager.user.getPassword();
		returned += " sending the following data:" + this.data;
		return returned;
	}
	
	public String toMessageString() {
		String returned;
		returned = "user=" + Activa.myMobileManager.user.getName();
		returned += "&pwd=" + Activa.myMobileManager.user.getPassword();
		returned += "&data=" + this.data;
		return returned;
	}
	
	public static Message extractMessage(String msg) {
		Message returned = new Message();
		int index1, index2;
		index1 = msg.indexOf('=')+1;
		index2 = msg.indexOf('&', index1);
		index1 = msg.indexOf('=', index2)+1;
		index2 = msg.indexOf('&', index1);
		index1 = msg.indexOf('=', index2)+1;
		returned.setData(msg.substring(index1));
		return returned;
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}
	
}
